services:
  react:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app       # Mount code for live reload
      - /usr/src/app/node_modules  # Ignore local node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  